<?php /** @var $this \Parable\Framework\View */ ?>

<h4>
    Players
    <a href="<?=$this->toolkit->getFullRouteUrlByName("add-player");?>">
        <i class="fa fa-fw fa-user-plus tally-button tally-add-player"></i>
    </a>
    <a href="<?=$this->toolkit->getFullRouteUrlByName("add-tally");?>">
        <i class="fa fa-fw fa-plus tally-button tally-add-tally"></i>
    </a>
    <a href="<?=$this->toolkit->getFullRouteUrlByName("exports");?>">
        <i class="fa fa-fw fa-code tally-button"></i>
    </a>
</h4>

<?php
$players = $this->internal->get("players");
foreach ($players as $player) {
    ?>
    <a class="big-link" href="<?=$this->toolkit->getFullRouteUrlByName("player", ["playerId" => $player->id]);?>">
        <?=$player->name;?>
    </a>
    <?php
}