<?php /** @var $this \Parable\Framework\View */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?=$this->config->get("parable.app.title");?></title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <link href='<?=$this->url->getUrl('css/normalize.css');?>' rel='stylesheet' type='text/css'>
        <link href='<?=$this->url->getUrl('css/tally.css');?>' rel='stylesheet' type='text/css'>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script>
            var baseUrl = "<?=$this->url->getBaseUrl();?>";
            $(function() {
                $('.tally-controls-mutate').on('click', function() {
                    var playerTallyId = $(this).parents(".tally-controls").attr("data-playerTallyId");
                    var amountElement = $(this).parents(".tally-controls").find('.tally-controls-amount');
                    var amount        = amountElement.val();
                    var totalElement  = $(this).parents(".tally-controls").find(".tally-amount");

                    amountElement.val("");

                    if (amount == "") {
                        amount = 1;
                    } else {
                        if (typeof amount !== 'number' && (amount % 1) !== 0) {
                            return;
                        }
                        amount = parseInt(amount);
                    }

                    var url = baseUrl + "/mutate/" + playerTallyId + "/" + amount;
                    $.get(url, function() {
                        var currentAmount = parseInt(totalElement.html());
                        totalElement.html(currentAmount + amount);
                    });
                });
                $('.player-tally-button').on('click', function() {
                    var selected = $(this).hasClass('selected');
                    var playerId = $(this).attr("data-playerId");
                    var tallyId = $(this).attr("data-tallyId");

                    var url = baseUrl + "/add-tally-to-player/" + playerId + "/" + tallyId;
                    if (selected) {
                        url = baseUrl + "/remove-tally-from-player/" + playerId + "/" + tallyId;
                    }
                    var self = this;
                    $.get(url, function() {
                        $(self).find('.fa-check').toggle();
                    });
                });
            });
        </script>
    </head>
    <body>
        <header>
            <a href="<?=$this->url->getUrl();?>"><?=$this->config->get("parable.app.title");?></a>
        </header>

        <?php
        if ($this->sessionMessage->count() > 0) {
            ?>
            <div class="session-messages">
                <?php
                foreach ($this->sessionMessage->getClear() as $type => $messages) {
                    foreach ($messages as $message) {
                        ?>
                        <div class="session-message type-<?=$type;?>">
                            <?=$message;?>
                        </div>
                        <?php
                    }
                }
                ?>
            </div>
            <?php
        }
        ?>

        <section>
